apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db-root-password: cm9vdHBhc3N3b3Jk
  db-username: dXNlcm5hbWU=
  db-password: cGFzc3dvcmQ=
  db-name: ZGJuYW1l
 

