apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
spec:
  selector:
    matchLabels:
      app: mysql-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
        - name: mysql-exporter
          image: prom/mysqld-exporter:v0.13.0
          env:
            - name: DATA_SOURCE_NAME
              value: "root:rootpassword@(mysql-service:3306)/mydb"
          ports:
            - name: metrics
              containerPort: 9104
